# Generated by Django 5.0 on 2023-12-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id группы')),
                ('group_name', models.CharField(max_length=100, verbose_name='Имя группы')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id группы')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Имя группы')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
                'ordering': ['tag_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Имя пользователя')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Адрес электронной почты')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='media/profile/', verbose_name='Фотография профиля')),
                ('groups', models.ManyToManyField(blank=True, related_name='groups', to='dbtools.group')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id файла')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.IntegerField(verbose_name='Размер файла')),
                ('file_path', models.CharField(max_length=255, verbose_name='Путь до файла')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('tags', models.ManyToManyField(blank=True, related_name='tags', to='dbtools.tag')),
                ('users', models.ManyToManyField(related_name='users', to='dbtools.user')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['file_name'],
            },
        ),
    ]
