# Generated by Django 3.2.13 on 2023-11-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbtools', '0002_auto_20231124_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
