# Generated by Django 3.2.13 on 2023-11-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtools', '0003_remove_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Имя пользователя'),
        ),
    ]
