# Generated by Django 3.2.13 on 2023-11-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtools', '0005_auto_20231126_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/', verbose_name='Фотография профиля'),
        ),
    ]
