# Generated by Django 3.2.13 on 2023-11-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbtools', '0006_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Фотография профиля'),
        ),
    ]
