# Generated by Django 4.2.7 on 2023-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dbtools", "0007_alter_user_profile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "group_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id группы"
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=100, verbose_name="Имя группы"),
                ),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "ordering": ["group_name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "tag_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id группы"
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(max_length=100, verbose_name="Имя группы"),
                ),
            ],
            options={
                "verbose_name": "Тэг",
                "verbose_name_plural": "Тэги",
                "ordering": ["tag_name"],
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/profile/",
                verbose_name="Фотография профиля",
            ),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "file_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Id файла"
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                ("file_size", models.IntegerField(verbose_name="Размер файла")),
                (
                    "file_path",
                    models.CharField(max_length=255, verbose_name="Путь до файла"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее изменение"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="dbtools.tag"
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(related_name="users", to="dbtools.user"),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
                "ordering": ["file_name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="dbtools.group"
            ),
        ),
    ]
